apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketball-activity-tracking-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basketball-activity-tracking
  template:
    metadata:
      labels:
        app: basketball-activity-tracking
    spec:
      containers:
        - image: lgaljo/rt_basketball_activity_tracking:latest
          name: basketball-activity-tracking
          env:
            - name: KUMULUZEE_CONFIG_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
              value: http://etcd:2379
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://ella.db.elephantsql.com/vkafqezn
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: vkafqezn
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass-activity
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8082
              name: server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 60
            periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: basketball-activity-tracking
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: basketball-activity-tracking